/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import javax.swing.JOptionPane;
import static view.Login.conta;

/**
 *
 * @author antonio
 */
public class SaqueFacil extends javax.swing.JFrame {

    /**
     * Creates new form SaqueFacil
     */
    public SaqueFacil() {
        initComponents();
    }
    
    public static boolean validado = false;
    public static String val;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_vinte = new javax.swing.JButton();
        btn_cinquenta = new javax.swing.JButton();
        btn_cem = new javax.swing.JButton();
        btn_trezentos = new javax.swing.JButton();
        btn_mil = new javax.swing.JButton();
        btn_seissentos = new javax.swing.JButton();
        btn_novecentos = new javax.swing.JButton();
        btn_dez = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        txt_valor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 640));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(10, 182, 155));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 640));

        btn_vinte.setBackground(new java.awt.Color(9, 131, 112));
        btn_vinte.setForeground(java.awt.Color.white);
        btn_vinte.setText("20,00");
        btn_vinte.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_vinte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vinteMouseClicked(evt);
            }
        });

        btn_cinquenta.setBackground(new java.awt.Color(9, 131, 112));
        btn_cinquenta.setForeground(java.awt.Color.white);
        btn_cinquenta.setText("50,00");
        btn_cinquenta.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_cinquenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cinquentaMouseClicked(evt);
            }
        });

        btn_cem.setBackground(new java.awt.Color(9, 131, 112));
        btn_cem.setForeground(java.awt.Color.white);
        btn_cem.setText("100,00");
        btn_cem.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_cem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cemMouseClicked(evt);
            }
        });

        btn_trezentos.setBackground(new java.awt.Color(9, 131, 112));
        btn_trezentos.setForeground(java.awt.Color.white);
        btn_trezentos.setText("300,00");
        btn_trezentos.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_trezentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_trezentosMouseClicked(evt);
            }
        });

        btn_mil.setBackground(new java.awt.Color(9, 131, 112));
        btn_mil.setForeground(java.awt.Color.white);
        btn_mil.setText("1000,00");
        btn_mil.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_mil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_milMouseClicked(evt);
            }
        });

        btn_seissentos.setBackground(new java.awt.Color(9, 131, 112));
        btn_seissentos.setForeground(java.awt.Color.white);
        btn_seissentos.setText("600,00");
        btn_seissentos.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_seissentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seissentosMouseClicked(evt);
            }
        });

        btn_novecentos.setBackground(new java.awt.Color(9, 131, 112));
        btn_novecentos.setForeground(java.awt.Color.white);
        btn_novecentos.setText("900,00");
        btn_novecentos.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_novecentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_novecentosMouseClicked(evt);
            }
        });

        btn_dez.setBackground(new java.awt.Color(9, 131, 112));
        btn_dez.setForeground(java.awt.Color.white);
        btn_dez.setText("10,00");
        btn_dez.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_dez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dezMouseClicked(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(34, 172, 26));
        jButton22.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton22.setForeground(java.awt.Color.black);
        jButton22.setText("Sacar");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Valor (R$):");

        jButton12.setBackground(java.awt.Color.cyan);
        jButton12.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton12.setForeground(java.awt.Color.black);
        jButton12.setText("Voltar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(213, 207, 42));
        jButton23.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton23.setForeground(java.awt.Color.black);
        jButton23.setText("Corrigir");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });

        txt_valor.setEditable(false);
        txt_valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt_valor.setText("00,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_dez, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btn_vinte, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btn_cinquenta, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btn_cem, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_trezentos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btn_seissentos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btn_novecentos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btn_mil, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_dez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_trezentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_vinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_seissentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novecentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cinquenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22)
                    .addComponent(jButton12)
                    .addComponent(jButton23))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, 644, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void btn_dezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dezMouseClicked
        txt_valor.setText("10,00");
        val = "10";
    }//GEN-LAST:event_btn_dezMouseClicked

    private void btn_vinteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vinteMouseClicked
        txt_valor.setText("20,00");
        val = "20";

    }//GEN-LAST:event_btn_vinteMouseClicked

    private void btn_cinquentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cinquentaMouseClicked
        txt_valor.setText("50,00");
        val = "50";

    }//GEN-LAST:event_btn_cinquentaMouseClicked

    private void btn_cemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cemMouseClicked
        txt_valor.setText("100,00");
        val = "100";

    }//GEN-LAST:event_btn_cemMouseClicked

    private void btn_trezentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trezentosMouseClicked
        txt_valor.setText("300,00");
        val = "300";

    }//GEN-LAST:event_btn_trezentosMouseClicked

    private void btn_seissentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seissentosMouseClicked
        txt_valor.setText("600,00");
        val = "600";

    }//GEN-LAST:event_btn_seissentosMouseClicked

    private void btn_novecentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novecentosMouseClicked
        txt_valor.setText("900,00");
        val = "900";

    }//GEN-LAST:event_btn_novecentosMouseClicked

    private void btn_milMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_milMouseClicked
        txt_valor.setText("1000,00");
        val = "1000";

    }//GEN-LAST:event_btn_milMouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        this.dispose();
        Menu menu = new Menu();
        menu.pack();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        txt_valor.setText("00,00");

    }//GEN-LAST:event_jButton23MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        Double valor = Double.parseDouble(val);
        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Efetuar saque no valor de " + val + "?","confirmar", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            if(valor <= conta.getSaldo()){
//                String inputValue = JOptionPane.showInputDialog(“Please input a value”);
                ConfirmaSenha cs = new ConfirmaSenha();
                cs.pack();
                cs.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Seu saldo é insuficiente para efetuar essa operação");

            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada");
        }
    }//GEN-LAST:event_jButton22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaqueFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaqueFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaqueFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaqueFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaqueFacil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cem;
    private javax.swing.JButton btn_cinquenta;
    private javax.swing.JButton btn_dez;
    private javax.swing.JButton btn_mil;
    private javax.swing.JButton btn_novecentos;
    private javax.swing.JButton btn_seissentos;
    private javax.swing.JButton btn_trezentos;
    private javax.swing.JButton btn_vinte;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
